added getPokemon method for getting pokemon with id. tests in progres…
aleviel/PokemonDesk pull request #7
Opened 2021-05-30 19:21 UTC by aleviel

чет я запутался немного в том, что накрутили в getUrlWithParams ...
тесты кручу пока еще ... не все получается и доходит.

2021-05-30 20:38 UTC, aleviel commented
дописал toCapitalizeFirstLetter.

2021-05-30 20:57 UTC, aleviel commented
не дойдет ... как передать в функцию toCapitalizeFirstLetter в компоненте pokemon имя, если его берем из data? без функции работало вот так data && data.name
в интерфейсе указано, что name это string. но как не передавай в качестве аргумента - не получается. 
toCapitalizeFirstLetter(data.name) -  Object is possibly 'null'
toCapitalizeFirstLetter(data?.name - Type 'undefined' is not assignable to type 'string'
toCapitalizeFirstLetter(data && data?.name) -  Type 'null' is not assignable to type 'string'.
toCapitalizeFirstLetter(data && data.name) -  Type 'null' is not assignable to type 'string'.

2021-05-31 12:57 UTC, ZarMarathon commented
так задай просто как дефолтное значение для параметра пустую строку и передавай как data?.name

2021-05-31 12:58 UTC, ZarMarathon requested changes
в уроке были и тесты для компонентов, я должен увидеть твоё понимание этой темы, так что сделай для одного какого-нибудь компонента тест, ну и настрой jest под css модули

2021-05-31 19:33 UTC, aleviel commented
дописал тесты для toCapitalizeFirstLetter. пока писал тесты, понял, что рассматриваю не все кейсы ... написал для них тесты и дополнил под них функцию.
написал тесты для Heading компонента. для разных пропсов. для наличия css. children. и просто дефолтного варианта без пропсов. 
чет даже понравилось с тестами ... помогли сейчас найти багу в функции сразу ...

2021-05-31 20:28 UTC, aleviel commented
пописал тестов для Button. все ок, что она рендерится, как рендерится по дефолту, как с разными пропсами. основы понял, дальше просто ищешь что нужно) а там в целом про тесты в доке Jest и доке React в части тестирования очень хорошо и понятно все расписано. 
вопрос. вот я протестировал, что кнопка вообще кликается. toHaveBeenCalledTimes. круто, кликается. но, у нас на кнопке висит событие, например на странице Home, которое нас отправит на другую страницу, это же мы протестировать не можем? или можем? не нашел таких решений

2021-05-31 22:18 UTC, ZarMarathon commented
это не нужно тестировать, функция navigate протестирована создателями роутера) тебе главное для компонента, что он вызывает всё, что должен тогда, когда должен

2021-05-31 22:19 UTC, ZarMarathon approved these changes
аппрув)

2021-06-01 05:24 UTC, merged